name: bovine-igg
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - seqkit>=2.4.0
  - bbmap>=39.01
  - blast>=2.14.0
  - csvtk>=0.25.0
  - pip
  - pip:
    - biopython
